title: Honors
description: List of AI honored papers
keywords: "honors, AI, papers, best-paper, outstanding-paper, distinguished-paper"
author:
  name: Junbo Wang
  email: sjtuwjb3589635689@sjtu.edu.cn
  url: "https://dadadadawjb.github.io"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

logo: "/assets/logo.png"
favicon_ico: "/assets/logo.png"

search_enabled: true

aux_links:
  "Honors on GitHub":
    - "//github.com/dadadadawjb/honors"
aux_links_new_tab: true

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
math: mathjax
